
# Learning Docker
# by @thepeg
# https://github.com/marcopeg/learning-docker

# Which NodeJS version do we need for our app
FROM nginx:1.11

# What files do we need to run our app?
COPY www /usr/share/nginx/html
